Metodos de pago
alejjandrotr/cineUDONE2024 pull request #5
Opened 2024-11-06 22:22 UTC by JesusMarichal

incluye los demas metodos de pago que seran usados en el sistema.

2024-11-11 16:57 UTC, JesusMarichal commented
validaciones de los DTO en "Metodos de pago".

2024-11-13 14:40 UTC, alejjandrotr requested changes

2024-11-13 14:40 UTC, alejjandrotr commented on apps/back-venta-boletos/src/app/pago-movil/pago-movil.entity.ts
> +//NOTA: LOS ARCHIVOS QUE SON .SPEC SON ARCHIVOS DE PRUEBA DE ARCHIVOS ARTERIORES, BASICAMENTE ES PARA SABER
Eliminar

2024-11-13 14:40 UTC, alejjandrotr commented on apps/back-venta-boletos/src/app/pago-movil/pago-movil.service.ts
> +export class pago_movil_service {
Cambia a cammelCase el nombre

2024-11-13 14:40 UTC, alejjandrotr commented on apps/back-venta-boletos/src/app/pago-movil/pago-movil.entity.ts
> +  numero_telef: string;
agregar la cedula y el numero de banco

2024-11-13 14:40 UTC, alejjandrotr commented on apps/back-venta-boletos/src/app/pago-movil/pago-movil.service.ts
> +  create_pago_movil(createpagomovil: create_pago_movil){
cammelCase

2024-11-13 14:40 UTC, alejjandrotr commented on apps/back-venta-boletos/src/app/pago-transferencia/dto/create-pago-transferencia.dto.ts
> +  nro_cuenta: string;
cammelCase

2024-11-13 14:40 UTC, alejjandrotr commented on apps/back-venta-boletos/src/app/pago-transferencia/pago-transferencia.controller.ts
> +  createPagoTransferencia(@Body() newPagoTransferencia: CreatePagoTransferenciadto) {
el nombre es redundante

2024-11-23 17:03 UTC, JesusMarichal commented
Profe disculpeme por la demora.

2024-11-29 14:27 UTC, merged